Use openshift-installer for cluster creation and deletion
RedHatQE/managed-services-integration-tests pull request #346
Opened 2023-08-16 16:09 UTC by rnetser

##### Short description:

##### More details:

##### What this PR does / why we need it:

##### Which issue(s) this PR fixes:

##### Special notes for reviewer:

##### Bug:

2023-08-16 19:22 UTC, myakove requested changes
please change 
BASIC_LOGGER to `BASIC_LOGGER = logging.getLogger("basic")` in conftest.py

2023-08-16 19:26 UTC, myakove requested changes

2023-08-16 19:26 UTC, myakove commented on tests/hypershift/test_hypershift.py
> +            pytest.fail(f"Failed to create cluster on {result.output}")
pytest.fail(f"Failed to destroy cluster. error:  {result.output}")

2023-08-16 19:43 UTC, rnetser commented on tests/hypershift/test_hypershift.py
> +            pytest.fail(f"Failed to create cluster on {result.output}")
done

2023-08-17 08:20 UTC, myakove approved these changes

2023-08-17 10:00 UTC, rnetser commented
/verified

2023-08-17 11:01 UTC, myakove approved these changes

2023-08-17 11:01 UTC, merged