Revert "Revert "Verify nodes have no resource pressure""
RedHatQE/managed-services-integration-tests pull request #45
Opened 2023-02-12 06:44 UTC by myakove

Reverts RedHatQE/managed-services-integration-tests#33

Depends on https://github.com/RedHatQE/openshift-python-utilities/pull/113

2023-02-12 16:32 UTC, rnetser requested changes

2023-02-12 16:32 UTC, rnetser commented on utilities/infra.py
>      assert_nodes_ready,
`assert_nodes_ready` can be removed; covered in `assert_nodes_in_healthy_condition`

2023-02-27 15:09 UTC, myakove commented
!verified

2023-02-28 10:51 UTC, rnetser approved these changes

2023-02-28 10:53 UTC, merged